name: API Token Monitor

on:
  schedule:
    # Runs every 30 minutes
    - cron: "*/30 * * * *"
  # Manual trigger option
  workflow_dispatch:

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Add Node.js setup for email functionality
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Call API and send notifications
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          # Make the API request and store the response
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -H "HTTP-Referer: https://aihime.app" \
            -H "X-Title: Aihime Anime Chat App" \
            -d '{
              "model": "meta-llama/llama-4-scout",
              "messages": [
                {
                  "role": "system", 
                  "content": "Say Hi"
                }
              ]
            }' \
            https://openrouter.ai/api/v1/chat/completions)
            
          # Format the response for Discord (escape quotes for JSON)
          FORMATTED_RESPONSE=$(echo $RESPONSE | jq -r tostring | sed 's/"/\\"/g')
          
          # Get current timestamp
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
          
          # Check if response contains "request requires more credits"
          if echo "$RESPONSE" | grep -q "request requires more credits"; then
            # Send tokens exhausted notification to Discord
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"content\": \"⚠️ **ALERT: Tokens Exhausted - $TIMESTAMP** ⚠️\n\nAPI credits have been depleted. Please recharge your account.\"}" \
              $DISCORD_WEBHOOK_URL
              
            # Set tokens exhausted flag for email notification
            echo "TOKENS_EXHAUSTED=true" >> $GITHUB_ENV
          else
            # Send regular response to Discord webhook is commented out
            # curl -X POST -H "Content-Type: application/json" \
            #   -d "{\"content\": \"**API Token Check - $TIMESTAMP**\n\`\`\`json\n$FORMATTED_RESPONSE\n\`\`\`\"}" \
            #   $DISCORD_WEBHOOK_URL
            
            # Workflow will only send notification when tokens are exhausted
            echo "API check completed, tokens not exhausted. No notification sent."
            echo "TOKENS_EXHAUSTED=false" >> $GITHUB_ENV
          fi
      
      - name: Send Email Notification
        if: env.TOKENS_EXHAUSTED == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "⚠️ ALERT: API Tokens Exhausted"
          body: |
            API Token Monitor has detected that your OpenRouter API credits have been depleted.
            
            Please recharge your account to continue using the service.
            
            Time of detection: $(date "+%Y-%m-%d %H:%M:%S")
            
            --
            This is an automated notification from API Token Monitor.
          to: ${{ secrets.GMAIL_RECIPIENT }}
          from: API Token Monitor <${{ secrets.GMAIL_USERNAME }}>