name: API Token Monitor

on:
  schedule:
    # Runs every 30 minutes
    - cron: "*/30 * * * *"
  # Manual trigger option
  workflow_dispatch:

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Call API and send to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Make the API request and store the response
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -H "HTTP-Referer: https://aihime.app" \
            -H "X-Title: Aihime Anime Chat App" \
            -d '{
              "model": "meta-llama/llama-4-scout",
              "messages": [
                {
                  "role": "system", 
                  "content": "Say Hi"
                },
                {
                  "role": "user",
                  "content": "Tell me how many tokens remaining"
                }
              ]
            }' \
            https://openrouter.ai/api/v1/chat/completions)
            
          # Format the response for Discord (escape quotes for JSON)
          FORMATTED_RESPONSE=$(echo $RESPONSE | jq -r tostring | sed 's/"/\\"/g')
          
          # Get current timestamp
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
          
          # Send to Discord webhook
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"**API Token Check - $TIMESTAMP**\n\`\`\`json\n$FORMATTED_RESPONSE\n\`\`\`\"}" \
            $DISCORD_WEBHOOK_URL